# Generated by Django 5.1.6 on 2025-03-24 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Szyfrowanie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plik',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plik',
            name='klucz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
