# Generated by Django 5.1.6 on 2025-05-19 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Szyfrowanie', '0002_plik_date_created_plik_klucz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plik',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 10, 17, 32, 448329)),
        ),
        migrations.AlterField(
            model_name='plik',
            name='klucz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
